services:
  django:
    build: .
    command:
      python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/djangogirls
    depends_on:
      - pgdb

  pgdb:
      image: postgres:13
      volumes:
        - .:/djangogirls
      environment:
        - "POSTGRES_HOST_AUTH_METHOD=trust"
